### ISSUE TITLE
What's the status of this package?

### ISSUE THREAD

**Issue by ghost** [alphapapa/frame-purpose.el#1]
I've installed from github and I'm able to make new frames per directory, mode etc... but nothing seem to happen then when I open files... it all seems to happen in the main frame rather than in the dedicated frame...

**Comment by alphapapa** [comment]
Please note from the readme that buffers are not locked to certain frames, nor are frames locked to certain buffers.  It only works by limiting what buffers are listed in purpose-specific frames.  If you open a file in a frame, it will be shown in that frame.

**Comment by ghost** [comment]
I’ll need to re-read the README :)
