### ISSUE TITLE
`icon-type` parameter doesn't work

### ISSUE THREAD

**Issue by hron** [alphapapa/frame-purpose.el#19]
I'm trying to create a frame with different icon-type, but it seems `icon-type` parameter has no effect:

![image](https://user-images.githubusercontent.com/39293/197839835-e2ee96ca-d3e1-4984-a5c8-4927377f3bdc.png)

```emacs-lisp
(frame-purpose-make-frame :modes 'org-mode
                          :title "Org"
                          :icon-type "/usr/share/icons/Yaru/256x256/apps/to-do-app.png")
```

```shell
➜  file /usr/share/icons/Yaru/256x256/apps/to-do-app.png
/usr/share/icons/Yaru/256x256/apps/to-do-app.png: PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced
```

I've tried to create a frame using `emacsclient` with `icon-type` frame parameter as well, but the problem is the same. Any chance you know a solution? Thank you in advance!

**Comment by alphapapa** [comment]
Hi,

I'm afraid I can't help you with this problem.  I don't use this package anymore, and it might be a good idea to archive the project, given its limitations.  Generally I'd recommend using Bufler to get similar features: https://github.com/alphapapa/bufler.el

But if you do want to use this, it shouldn't be difficult to inspect the source code and find out what's going on.

However, I see that you're using DOOM, which is likely related to the problem you're having.  I'd suggest trying to reproduce the problem in a clean Emacs config, e.g. using https://github.com/alphapapa/with-emacs.sh

**Comment by hron** [comment]
@alphapapa Thank you very much for the detailed response!
