### ISSUE TITLE
Unable to show a sidebar

### ISSUE THREAD

**Issue by akirak** [alphapapa/frame-purpose.el#2]
When I create a frame using `frame-purpose-make-mode-frame` and try to show a sidebar using `frame-purpose-show-sidebar`, the following error is shown:

> Wrong type arguent: char-or-string-p, nil

Then Emacs becomes unable to do anything that requires opening a new window, e.g. Ivy. The following error is shown whenever I perform such an operation. 

A more detailed error is shown in `*Messages*`:

> frame-purpose--buffer-list-update-hook: Wrong type arguent: char-or-string-p, nil

I could not further identify the error.

**Comment by alphapapa** [comment]
I think that should fix it.  Thanks very much for reporting so quickly!

**Comment by alphapapa** [comment]
By the way, in the future, if you encounter any problems like this, you should be able to make Emacs work correctly again by disabling `frame-purpose-mode`.  If necessary, you can try to do this from outside Emacs, if you're using `emacsclient`, like this:

```
$ emacsclient --eval '(frame-purpose-mode -1)'
```

I had to do that occasionally while debugging things.  :)

**Comment by alphapapa** [comment]
Oh, and in general, you can get backtraces by running `toggle-debug-on-error` and doing whatever caused the error again.  I was able to figure it out without the backtrace, but some bugs are harder to track down.  :)

**Comment by akirak** [comment]
Thank you!

The problem did not happen until I tried to open a sidebar, so I ran it in a separate Emacs instance. I could not display the backtrace buffer, because the buffer does not exist until an error happens, and once the error happened, I could not switch to the buffer...
