### ISSUE TITLE
Dependency error for dash-functional

### ISSUE THREAD

**Issue by rieje** [alphapapa/frame-purpose.el#4]
Using `use-package`, I'm getting a dependency error for dash-functional with:

(use-package frame-purpose :ensure nil). 

> Error (use-package): frame-purpose/:catch: Cannot open load file: No such file or directory, dash-functional

Similar error exists when using `require`. No problems after installing `dash-functional` manually, but `frame-purpose` should handle that dependency, right?

**Comment by alphapapa** [comment]
Oops, I forgot that dash-functional is a separate package.  Thank you!
